const default_font = [
  "Arial",
  "Helvetica",
  "Times New Roman",
  "Georgia",
  "Verdana",
  "Courier New",
  "Microsoft YaHei",
  "SimSun",
  "SimHei",
  "PingFang SC",
  "Hiragino Sans GB",
  "Noto Sans SC",
  "Noto Serif SC",
  "Source Han Sans SC",
  "STSong",
  "STKaiti",
  "KaiTi",
  "FangSong",
  "Comic Sans MS",
  "Impact",
  "Trebuchet MS",
  "Tahoma",
  "Palatino Linotype",
  "Lucida Console",
  "Segoe UI",
];

export { default_font };
